# Generated by Django 4.1.1 on 2022-12-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(blank=True)),
                ('updatedAt', models.DateTimeField(blank=True)),
            ],
        ),
    ]
