# Generated by Django 4.1.1 on 2022-12-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_adult', models.IntegerField(default=0)),
                ('number_children', models.IntegerField(default=0)),
                ('number_baby', models.IntegerField(default=0)),
                ('payment_methods', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('phoneNumber', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=255)),
                ('total', models.IntegerField(default=0)),
                ('tour_code', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(blank=True)),
                ('updatedAt', models.DateTimeField(blank=True)),
            ],
        ),
    ]
