# Generated by Django 4.1.1 on 2022-12-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('tour_code', models.CharField(max_length=255)),
                ('start', models.DateField(default=None)),
                ('end', models.DateField(default=None)),
                ('price_adult', models.IntegerField(default=0)),
                ('price_children', models.IntegerField(default=0)),
                ('price_baby', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(blank=True)),
                ('updatedAt', models.DateTimeField(blank=True)),
            ],
        ),
    ]
